// Bingo Nicknames Data
// Format: number: { nickname: "...", explanation: "..." }
const bingoNicknames = {
    1: { nickname: "Kelly's eye", explanation: "The pun is military slang; possibly a reference to Ned Kelly, from Ned Kelly's helmet, the eye slot resembling the number 1." },
    2: { nickname: "One little duck", explanation: "From the resemblance of the number 2 to a duck; see also \"22\". Response is a single \"quack.\"" },
    3: { nickname: "Cup of tea", explanation: "Rhymes with \"three\"." },
    4: { nickname: "Knock at the door", explanation: "From the Nursery rhyme One, Two, Buckle my shoe; Three, Four, Knock at the door." },
    5: { nickname: "Man alive", explanation: "Rhymes with \"five\"." },
    6: { nickname: "Half a dozen", explanation: "A common phrase meaning six units (see \"12\" below)." },
    7: { nickname: "Lucky", explanation: "7 is considered a lucky number in some cultures; see also \"73\"." },
    8: { nickname: "Garden gate", explanation: "Rhymes with \"eight\"." },
    9: { nickname: "Brighton line", explanation: "A reference to the British railway line running from London Victoria and London Bridge to Brighton." },
    10: { nickname: "Keir's den", explanation: "The name refers to 10 Downing Street, the home of the UK Prime Minister." },
    11: { nickname: "Legs eleven", explanation: "A reference to the shape of the number resembling a pair of legs, often chicken legs specifically. The players often wolf whistle in response." },
    12: { nickname: "One dozen", explanation: "A reference to there being 12 units in one dozen." },
    13: { nickname: "Unlucky for some", explanation: "A reference to 13 being an unlucky number." },
    14: { nickname: "Valentine's Day", explanation: "A reference to 14 February being St. Valentine's Day." },
    15: { nickname: "Young and keen", explanation: "Rhymes with \"fifteen\"." },
    16: { nickname: "Never been kissed", explanation: "After the song Sweet Sixteen and Never Been Kissed." },
    17: { nickname: "Dancing Queen", explanation: "The song \"Dancing Queen\" by ABBA famously features the number in its lyrics." },
    18: { nickname: "Coming of age", explanation: "Eighteen is the age of majority in the England, Wales and Northern Ireland." },
    19: { nickname: "Goodbye, teens", explanation: "Nineteen is the age after which a person stops being a teenager." },
    20: { nickname: "Getting plenty", explanation: "cheeky phrase- rhymes with twenty" },
    21: { nickname: "Key of the door", explanation: "The traditional age of majority." },
    22: { nickname: "Two little ducks", explanation: "The numeral 22 resembles the profile of two ducks. Response is often \"quack, quack, quack\"." },
    23: { nickname: "The Lord is My Shepherd", explanation: "The first words of Psalm 23 of the Old Testament." },
    24: { nickname: "Two dozen", explanation: "12 × 2 = 24. Refer to 12 above." },
    25: { nickname: "Duck and dive", explanation: "Rhymes with \"(twenty) five\", and is made up of a \"2\" – resembles a duck, and a \"5\" – resembles a reflected \"2\"." },
    26: { nickname: "Pick and mix", explanation: "Rhymes with \"twenty-six\"." },
    27: { nickname: "Gateway to Heaven", explanation: "Rhymes with \"twenty-seven\"." },
    28: { nickname: "Overweight", explanation: "Rhymes with \"twenty-eight\"." },
    29: { nickname: "Rise and shine", explanation: "Rhymes with \"twenty-nine\"." },
    30: { nickname: "Dirty Gertie", explanation: "Common rhyme derived from the given name Gertrude, used as a nickname for the statue La Delivrance installed in North London in 1927." },
    31: { nickname: "Get up and run", explanation: "Rhymes with \"thirty-one\"." },
    32: { nickname: "Buckle my shoe", explanation: "Rhymes with \"thirty-two\"." },
    33: { nickname: "Dirty knee", explanation: "Rhymes with \"thirty-three\"." },
    34: { nickname: "Ask for more", explanation: "Rhymes with \"thirty-four\"." },
    35: { nickname: "Jump and jive", explanation: "A dance step." },
    36: { nickname: "Three dozen", explanation: "3 × 12 = 36. Refer to 12 above." },
    37: { nickname: "More than 11", explanation: "Rhymes with \"thirty-seven\"." },
    38: { nickname: "Christmas cake", explanation: "Cockney rhyming slang." },
    39: { nickname: "Steps", explanation: "From the 39 Steps" },
    40: { nickname: "Life begins", explanation: "Refers to the proverb 'life begins at forty'." },
    41: { nickname: "Time for fun", explanation: "Rhymes with \"forty-one\"." },
    42: { nickname: "Winnie the Pooh", explanation: "Rhymes with \"forty-two\" and in reference to Winnie-the-Pooh, a beloved UK children's book character." },
    43: { nickname: "Down on your knees", explanation: "This was a phrase that was made popular during wartime by soldiers." },
    44: { nickname: "Droopy drawers", explanation: "Rhyme that refers to sagging underwear." },
    45: { nickname: "Halfway there", explanation: "Being halfway towards 90." },
    46: { nickname: "Up to tricks", explanation: "Rhymes with \"forty-six\"." },
    47: { nickname: "Four and seven", explanation: "Refers to the two numbers that make up 47, those being 4 and 7." },
    48: { nickname: "Four dozen", explanation: "4 × 12 = 48. Refer to 12 above." },
    49: { nickname: "PC", explanation: "Refers to the BBC Radio series \"The Adventures of PC 49\". Usual response is \"Evening, all\"." },
    50: { nickname: "It's a bullseye!", explanation: "Referring to the darts score." },
    51: { nickname: "Tweak of the thumb", explanation: "Rhymes with \"fifty-one\"." },
    52: { nickname: "Deck of cards", explanation: "Number of cards in a deck." },
    53: { nickname: "Here comes Herbie!", explanation: "53 is the racing number of Herbie the VW Beetle. Players may reply \"beep beep!\"." },
    54: { nickname: "Man at the door", explanation: "Rhymes with \"fifty-four\"." },
    55: { nickname: "Snakes alive", explanation: "Rhymes with \"fifty-five\"." },
    56: { nickname: "Was she worth it?", explanation: "This refers to the pre-decimal price of a marriage licence in Britain, 5/6d. The players shout back \"Every Penny!\"" },
    57: { nickname: "Heinz varieties", explanation: "Refers to \"Heinz 57\", the \"57 Varieties\" slogan of the H. J. Heinz Company." },
    58: { nickname: "Make them wait", explanation: "Rhymes with \"fifty-eight\". Here the announcer would pause, making the audience wait." },
    59: { nickname: "Brighton line", explanation: "Quote from The Importance of Being Earnest referencing trains 59 in turn references the number 59 bus running between Brighton and Shoreham-by-Sea." },
    60: { nickname: "Grandma's getting frisky", explanation: "Rhymes with \"sixty\"." },
    61: { nickname: "Baker's bun", explanation: "Rhymes with \"sixty-one\"." },
    62: { nickname: "Tickety-boo", explanation: "Rhymes with \"sixty-two\"." },
    63: { nickname: "Tickle me", explanation: "Rhymes with \"sixty-three\"." },
    64: { nickname: "Almost retired", explanation: "A reference to the former British male age of mandatory retirement – specifically being one year away from it." },
    65: { nickname: "Retirement age", explanation: "A reference to the former male British age of mandatory retirement." },
    66: { nickname: "Clickety click", explanation: "Rhymes with \"sixty-six\"." },
    67: { nickname: "Stairway to Heaven", explanation: "Rhymes with \"sixty-seven\"." },
    68: { nickname: "Pick a mate", explanation: "Rhymes with \"sixty-eight\"." },
    69: { nickname: "Meal for two", explanation: "A reference to the 69 sex position." },
    70: { nickname: "Three score and 10", explanation: "A score is a way of counting in 20s in which one score is 20. (20 × 3 + 10 = 70.) Three score and ten years is the span of life according to the Bible." },
    71: { nickname: "Bang on the drum", explanation: "Rhymes with \"seventy-one\"." },
    72: { nickname: "Danny La Rue", explanation: "Rhymes with \"seventy-two\"" },
    73: { nickname: "Queen bee", explanation: "Rhymes with \"seventy-three\"." },
    74: { nickname: "Hit the floor", explanation: "Rhymes with \"seventy-four\"." },
    75: { nickname: "Strive and strive", explanation: "Rhymes with \"seventy-five\"." },
    76: { nickname: "Trombones", explanation: "\"Seventy-Six Trombones\" is a popular marching song, from the musical The Music Man." },
    77: { nickname: "Sunset Strip", explanation: "From the 1960s television series \"77 Sunset Strip\". Usually sung by the players." },
    78: { nickname: "Heaven's gate", explanation: "Rhymes with \"seventy-eight\"." },
    79: { nickname: "One more time", explanation: "Rhymes with \"seventy-nine\"." },
    80: { nickname: "Gandhi's breakfast", explanation: "\"Ate nothing\"" },
    81: { nickname: "Stop and run", explanation: "Rhymes with \"eighty-one\"." },
    82: { nickname: "Straight on through", explanation: "Rhymes with \"eighty-two\"." },
    83: { nickname: "Time for tea", explanation: "Rhymes and scans" },
    84: { nickname: "Give me more", explanation: "Rhymes and scans." },
    85: { nickname: "Staying alive", explanation: "Rhymes with \"eighty-five\"." },
    86: { nickname: "Between the sticks", explanation: "Rhymes with \"eighty-six\". Refers to the position of goalkeeper in football." },
    87: { nickname: "Torquay in Devon", explanation: "Rhymes with \"eighty-seven\". Torquay which is in the county of Devon, rather than one of several other Torquays which were elsewhere in the British Empire." },
    88: { nickname: "Two fat ladies", explanation: "The number 88 visually resembles a lady next to another lady. Refer to 8 and 81 above. Players can reply with \"wobble, wobble!\"" },
    89: { nickname: "Nearly there", explanation: "89 is one away from 90 (the end of the bingo numbers)." },
    90: { nickname: "Top of the shop", explanation: "90 is the highest (top) number in bingo. Shop refers to the entire game of bingo (and also rhymes with \"top\")." }
};

// To make it accessible to script.js, this file would typically be included
// via a <script> tag in index.html before script.js, or its content
// would be directly part of script.js. For this environment, I'll assume
// its content is available to script.js.
